/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class', // matches Stitch's own <html class="dark"> convention
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Prism dark theme — pulled directly from the Stitch export's
        // Material-derived token names, so future Stitch exports using
        // the same design system drop in with matching class names.
        'on-tertiary-container': '#780047',
        'on-surface': '#e4e1e9',
        'on-error': '#690005',
        'on-primary': '#003640',
        'surface-container': '#1f1f25',
        'error-container': '#93000a',
        'inverse-surface': '#e4e1e9',
        'primary-fixed': '#acedff',
        'on-secondary-fixed-variant': '#653e00',
        secondary: '#ffb95f',
        'surface-bright': '#39383e',
        surface: '#131318',
        'on-background': '#e4e1e9',
        'on-primary-fixed': '#001f26',
        'inverse-on-surface': '#303036',
        'on-surface-variant': '#bcc9cd',
        error: '#ffb4ab',
        'secondary-container': '#ee9800',
        'on-primary-fixed-variant': '#004e5c',
        tertiary: '#ffb0cd',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-container': '#5b3800',
        'inverse-primary': '#00687a',
        outline: '#869397',
        primary: '#4cd7f6',
        'surface-container-high': '#2a292f',
        'surface-container-low': '#1b1b20',
        'tertiary-fixed-dim': '#ffb0cd',
        'on-tertiary': '#640039',
        background: '#131318',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#4cd7f6',
        'on-tertiary-fixed-variant': '#8c0053',
        'surface-dim': '#131318',
        'on-tertiary-fixed': '#3e0022',
        'secondary-fixed': '#ffddb8',
        'surface-container-lowest': '#0e0e13',
        'secondary-fixed-dim': '#ffb95f',
        'tertiary-container': '#ff79b4',
        'surface-container-highest': '#35343a',
        'tertiary-fixed': '#ffd9e4',
        'primary-container': '#06b6d4',
        'outline-variant': '#3d494c',
        'on-secondary': '#472a00',
        'surface-variant': '#35343a',
        'on-primary-container': '#00424f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0.005em', fontWeight: '400' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
